
export default function Bai6() {
  return (
    <p className="h-[200px] w-[500px] overflow-auto">Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates tempore assumenda deserunt ea facere magnam illum officia est nam, laudantium numquam placeat odit, sapiente eos doloribus consequatur sed rem modi!
    Praesentium sit perferendis placeat mollitia numquam quam ullam officia quae consectetur libero quasi voluptas perspiciatis ipsam quas aut, esse magni fugiat nulla, debitis nisi ipsum vitae corporis quo ea? Hic.
    Unde odit architecto sequi ipsam distinctio blanditiis maiores at harum quaerat excepturi corporis, ipsum expedita dolorem aspernatur tempora nihil. Nulla debitis deserunt id? Blanditiis ut recusandae excepturi enim nulla doloremque!
    Omnis optio ratione sunt error quos. Quaerat quod saepe ratione ducimus obcaecati rerum officia, doloremque molestiae praesentium sed nulla repellendus adipisci similique delectus totam vel! Commodi quasi atque expedita pariatur.
    Voluptatibus, laborum facere molestiae doloremque odit error quaerat inventore labore, eaque nostrum ipsam nulla ducimus totam non neque quisquam, sunt placeat numquam cumque sed atque beatae culpa assumenda? Ex, magni.
    Rem, enim. Nostrum odio magni eaque harum provident possimus reprehenderit vel repellat molestiae aspernatur, iure facere neque incidunt quia, ut quisquam quo ea architecto blanditiis laboriosam, nemo ullam. Pariatur, impedit.
    Adipisci labore iusto eius assumenda temporibus sit harum deserunt amet in quo, repellendus tempora perspiciatis, natus iste nesciunt dolor et veniam esse sint debitis tempore. Facilis laudantium tempore iusto provident.
    Quidem debitis ea quasi at natus ut aperiam, eum suscipit. Quasi quos pariatur sint sequi doloribus, hic consectetur nihil saepe aliquam! Eum fuga corporis assumenda cum incidunt porro nobis exercitationem!
    Dolores, magnam voluptatum libero asperiores omnis aperiam iste ab impedit eius numquam cumque, deleniti reprehenderit quam tempore, incidunt saepe? Beatae nam doloribus iste sapiente quibusdam omnis atque quasi eveniet rem!
    Consequuntur nisi assumenda eius facilis maxime quis sunt voluptatum quae totam recusandae unde distinctio perspiciatis culpa laboriosam, aut saepe tempore iure eos nobis molestiae in ullam ratione? Dolor, optio unde.
    Ea, cumque nam? Officia eos nulla maxime doloremque aliquam qui nobis recusandae ratione dignissimos placeat impedit earum magni, excepturi obcaecati blanditiis, officiis illum voluptate consectetur ad quibusdam nisi perspiciatis commodi.
    Et ut architecto aliquam quibusdam corporis velit voluptatibus possimus minima explicabo consequatur eaque, quis molestiae culpa molestias odio, exercitationem dolores dolore fugit ab! Eaque soluta eius dignissimos animi culpa magni.
    Dolorum aliquam similique qui recusandae voluptas, atque nisi vitae dolorem omnis incidunt quaerat cum consequatur sint reprehenderit? Ratione nemo obcaecati quod distinctio iste, nisi fugit ducimus temporibus quis et culpa!
    Ducimus repellat officiis, voluptate, facilis illum rerum, perspiciatis cupiditate exercitationem iure soluta fugiat recusandae quas et sequi repudiandae eum eaque! Inventore laudantium quia placeat maiores. Quaerat distinctio illo tenetur optio!
    Sequi, ea id. Quia, eum sapiente doloremque ipsa eius, voluptas saepe, tempore fugit amet modi assumenda. Minus, facere nostrum porro repudiandae commodi alias adipisci repellat, fuga consequatur deleniti aut doloremque?
    Repudiandae, architecto maxime necessitatibus sed quos nostrum qui, ullam quis non repellat illum nesciunt. Laborum animi vel corrupti nisi illo eius deserunt soluta, quae numquam, esse eum officiis temporibus sint?
    Iure magni laudantium enim ea impedit, tempore eius molestias velit odit deleniti vel consequuntur eos accusamus rerum. Doloremque nemo quas, veniam fugit aut magnam deserunt quisquam quod illum culpa est?
    Cumque architecto fugit qui placeat unde quis illo vel perferendis odit beatae accusamus, laborum culpa ullam eveniet ea velit repudiandae corporis facere, magnam dignissimos quam explicabo quia eaque! Molestias, veritatis!
    Cum cumque modi hic accusamus repudiandae alias, cupiditate unde earum libero necessitatibus, praesentium aut inventore optio laudantium dolorum adipisci officiis, incidunt perspiciatis ex magni obcaecati ad. Velit ipsa accusantium sit.
    Accusantium eveniet quam velit delectus praesentium vel quasi. Autem consequatur quod, culpa quo exercitationem qui repudiandae itaque quaerat, optio, molestias rem laborum earum porro eligendi corrupti animi sunt. Voluptatem, quos?
    Quidem, suscipit? Nobis beatae esse veritatis quae facere fuga sit minima quas nisi, doloremque dolore quisquam delectus fugit officia saepe ullam at assumenda, neque quibusdam accusamus asperiores cumque! Necessitatibus, atque.
    Ipsum tenetur alias assumenda illo molestiae commodi ad sapiente minus eum veniam excepturi quam vel illum non exercitationem, pariatur quod unde. Aliquam, enim iusto eius quae dolorum voluptas iure necessitatibus?
    Eos aut accusantium expedita nam sequi dolore molestias numquam rem, quidem quas aliquid asperiores reprehenderit mollitia, recusandae explicabo ducimus necessitatibus in consequuntur sapiente praesentium ab, veritatis error nesciunt dolorem. Nulla?
    Eius assumenda, aliquid delectus, hic autem sit, quas harum deleniti animi corrupti exercitationem blanditiis voluptate. Molestiae veniam aperiam, voluptatum molestias, nobis dolore excepturi quos itaque minus, cumque similique sapiente nulla!
    Consequuntur, voluptatum voluptatem? Fugit libero ea hic voluptatem, nam fuga esse in mollitia explicabo. Totam cumque labore minima reprehenderit. Eveniet consequuntur error odit vitae assumenda quam officia nesciunt? Nobis, nesciunt.
    Ipsa et optio distinctio? Magnam similique esse qui, dignissimos ducimus dolorum quo ab voluptatum accusamus. Voluptates, incidunt in fugit dolorum et qui debitis, sit est neque quas adipisci aliquam animi?
    Aliquam, repudiandae consectetur. Iure omnis odio ullam impedit consequuntur, architecto beatae quos quod repellat ea natus necessitatibus labore recusandae in. Explicabo omnis architecto neque dolor porro eum quo asperiores earum!
    Culpa nesciunt, vel aperiam sequi sunt quo provident in inventore. Quae ullam tenetur atque eligendi aperiam optio modi voluptates officiis beatae sed, ipsum corrupti porro harum suscipit perferendis, sapiente fugit.
    Corporis cum perspiciatis a in! Delectus officiis esse tenetur fugit molestiae sit ratione facilis consequuntur maiores natus minima ipsum, dolor dignissimos. Architecto sint harum corporis odio hic deleniti sed quam!
    Ipsa consequuntur, assumenda officia dolor earum blanditiis tempore accusamus in soluta suscipit, rerum fuga, asperiores expedita adipisci? Quaerat, labore minima aliquid, reprehenderit optio quo accusantium eaque, nisi harum ex maxime.
    Officia deleniti ducimus quis recusandae enim a explicabo maiores excepturi rerum eos facere, dignissimos quidem corrupti dolores odit esse, non et voluptatum porro doloribus tempore. Culpa aperiam vel corporis esse?
    Totam sint, obcaecati cupiditate neque debitis vitae expedita, labore ratione corporis repellat quisquam deserunt magni? Exercitationem, accusamus aperiam officia tenetur veniam soluta ut similique, cupiditate vero nulla nobis at saepe!
    Esse impedit sit ipsum nulla. Maxime modi delectus minus odio quaerat accusamus maiores dolor aut labore dolores itaque reiciendis ex sunt recusandae qui eos nobis, beatae rem error id fugiat.
    Veritatis reprehenderit excepturi a illo quia laboriosam voluptates explicabo perferendis. Pariatur, aliquid. Doloremque recusandae, deleniti harum explicabo esse quis hic molestias nemo alias tempora veniam in, laboriosam libero laborum similique!
    Maiores magnam odit nostrum soluta, magni repudiandae quos a impedit sit totam nobis ratione, perferendis perspiciatis dolorem. Consequatur quae quos, quam voluptates, similique est voluptatem fugit nemo recusandae rerum maiores.
    Similique, quam magni illum, eligendi aliquam aspernatur veniam sint provident vel odio animi eius unde. Ex dolorem porro quae in repellat perferendis earum? Sapiente voluptas, ad cupiditate deserunt dolorum quaerat?
    Nesciunt soluta deserunt iusto odio praesentium eveniet omnis hic, quas ullam reprehenderit? Exercitationem ipsum, aliquid adipisci, voluptatibus eligendi dicta accusamus at vitae consequatur alias est amet deleniti consequuntur voluptas iure?
    Assumenda saepe debitis laudantium, praesentium non sit et officia qui est nulla earum commodi sed. Veniam iste animi tempora, natus porro pariatur esse, molestias vel nemo sequi officia incidunt excepturi.
    Similique, natus commodi repellendus voluptate nisi sequi pariatur nesciunt aliquid sapiente rem beatae itaque adipisci voluptatum quis aspernatur consectetur doloribus. Animi amet provident sint neque numquam optio nulla laudantium officiis.
    Excepturi id hic quas quam et cumque, quidem facere perferendis nesciunt perspiciatis sequi, consequuntur labore alias doloribus quo delectus corporis veniam, sit natus aperiam ipsam. Eos magni a corrupti perferendis.
    Voluptate aliquam fugit aliquid labore fuga unde, dolorum illum tempore repellat maiores harum qui in commodi, illo officia itaque blanditiis neque dolores nam numquam ullam. Sed, tempore? Dolore, quisquam cumque.
    Facere suscipit autem, id est deserunt voluptatem nobis pariatur cupiditate exercitationem, dolores animi aut ipsam quibusdam ea quod ad deleniti? Accusamus deleniti quod alias, vero ratione blanditiis recusandae ea inventore?
    Incidunt, assumenda laboriosam veniam excepturi earum nemo ratione modi perferendis autem harum similique dicta quae, animi quis nihil natus. Explicabo soluta nisi, illum voluptates quisquam magnam recusandae at ea quas.
    Ut soluta nobis eos adipisci iusto temporibus, illum repellat magni voluptatem quos quis earum cum cupiditate culpa. Repellendus impedit, aliquid asperiores quos beatae facere natus reiciendis odit, cupiditate dolorem eveniet.
    Nam non alias nostrum veniam rerum sed nesciunt nisi modi commodi. Iure minus eos, aspernatur cumque facere dolor, autem molestiae repellendus odio doloribus voluptates exercitationem animi tempora in, sed excepturi.
    Molestiae ea sunt blanditiis accusantium architecto nulla dolor, dignissimos impedit aspernatur dolorem? Quis commodi enim explicabo nobis consectetur asperiores nemo ipsa repellendus est fugiat, molestias velit eaque ipsum vitae expedita!
    Voluptatem placeat reiciendis deserunt, alias illum molestiae, officia nesciunt veritatis accusamus quibusdam nemo quaerat asperiores, amet doloremque sequi eveniet odio debitis itaque facilis libero est? Facere, laborum? Inventore, totam libero.
    Commodi eum explicabo incidunt vitae odio voluptates molestiae quas eligendi tempore facere mollitia libero reprehenderit aspernatur, nihil optio necessitatibus omnis! Neque iste corrupti quasi provident magni fuga odit inventore eligendi!
    Necessitatibus beatae, earum consectetur laboriosam quaerat unde, sapiente excepturi ducimus tempora similique omnis? Deserunt amet repellat voluptates, in inventore ducimus officiis quibusdam consectetur consequatur nobis culpa, expedita perspiciatis magni repellendus.
    Illo reprehenderit sequi veritatis voluptate optio atque assumenda cumque beatae voluptas quasi, ipsum doloribus excepturi, eius repellendus dolorum tempore architecto? Tempore eligendi in eius eveniet quisquam! Praesentium minus dolorum eveniet.</p>
  )
}